// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkejhefzzfhiahiibexa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZWpoZWZ6emZoaWFoaWliZXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjEyOTIsImV4cCI6MjA2NjIzNzI5Mn0.tQA0k771EWt3cfCl-Pd-PT9y9QVfYfLH6P3A6QYXArA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);